let MAGIC = 0x1A51504D; // MPQ\x1A reversed
let HASH_TABLE_KEY = 0xC3AF3770; // Hash of (hashtable)
let HASH_TABLE_INDEX = 0;
let HASH_NAME_A = 1;
let HASH_NAME_B = 2;
let HASH_FILE_KEY = 3;
let HASH_ENTRY_DELETED = 0xFFFFFFFE;
let HASH_ENTRY_EMPTY = 0xFFFFFFFF;
let BLOCK_TABLE_KEY = 0xEC83B3A3; // Hash of (blocktable)
let FILE_IMPLODE = 0x00000100;
let FILE_COMPRESSED = 0x00000200;
let FILE_ENCRYPTED = 0x00010000;
let FILE_OFFSET_ADJUSTED_KEY = 0x00020000;
let FILE_PATCH_FILE = 0x00100000;
let FILE_SINGLE_UNIT = 0x01000000;
let FILE_DELETE_MARKER = 0x02000000;
let FILE_SECTOR_CRC = 0x04000000;
let FILE_EXISTS = 0x80000000;
let COMPRESSION_HUFFMAN = 0x01;
let COMPRESSION_DEFLATE = 0x02;
let COMPRESSION_IMPLODE = 0x08;
let COMPRESSION_BZIP2 = 0x10;
let COMPRESSION_ADPCM_MONO = 0x40;
let COMPRESSION_ADPCM_STEREO = 0x80;

export {
  MAGIC,
  HASH_TABLE_KEY,
  HASH_TABLE_INDEX,
  HASH_NAME_A,
  HASH_NAME_B,
  HASH_FILE_KEY,
  HASH_ENTRY_DELETED,
  HASH_ENTRY_EMPTY,
  BLOCK_TABLE_KEY,
  FILE_IMPLODE,
  FILE_COMPRESSED,
  FILE_ENCRYPTED,
  FILE_OFFSET_ADJUSTED_KEY,
  FILE_PATCH_FILE,
  FILE_SINGLE_UNIT,
  FILE_DELETE_MARKER,
  FILE_SECTOR_CRC,
  FILE_EXISTS,
  COMPRESSION_HUFFMAN,
  COMPRESSION_DEFLATE,
  COMPRESSION_IMPLODE,
  COMPRESSION_BZIP2,
  COMPRESSION_ADPCM_MONO,
  COMPRESSION_ADPCM_STEREO,
};
