// Copyright (c) 2013 Chananya Freiman (aka GhostWolf)

var SHADERS = {
	"vsbonetexture":"\n#define RL texture2D\nuniform sampler2D L;uniform float M,N;mat4 A(float a){float b=a*M;return mat4(RL(L,vec2(a*M,0)),RL(L,vec2(b+N,0)),RL(L,vec2(b+N*2.,0)),RL(L,vec2(b+N*3.,0)));}",
	"vsworld":"uniform mat4 O;uniform vec2 P;attribute vec3 BE;attribute vec2 BF;varying vec2 BQ;void main(){BQ=BF+P;gl_Position=O*vec4(BE,1);}",
	"vswhite":"uniform mat4 O;attribute vec3 BE;void main(){gl_Position=O*vec4(BE,1);}",
	"psworld":"uniform sampler2D Q;uniform float R;varying vec2 BQ;void main(){gl_FragColor=vec4(texture2D(Q,BQ).rgb,R);}",
	"pswhite":"void main(){gl_FragColor=vec4(1);}",
	"wvsskinning":"\n#define BW attribute\nuniform mat4 O;uniform vec2 P;BW vec3 BE;BW vec2 BF;BW vec4 BG;BW float BH;varying vec2 BQ;void main(){vec4 b=vec4(BE,1);vec4 a=(A(BG[0])*b+A(BG[1])*b+A(BG[2])*b+A(BG[3])*b)/BH;BQ=BF+P;gl_Position=O*a;}",
	"wvssoftskinning":"uniform mat4 O;uniform vec2 P;attribute vec3 BE;attribute vec2 BF;varying vec2 BQ;void main(){BQ=BF+P;gl_Position=O*vec4(BE,1);}",
	"wvsparticles":"uniform mat4 O;attribute vec3 BE;attribute vec2 BF;attribute vec4 BI;varying vec2 BQ;varying vec4 BR;void main(){BQ=BF;BR=BI;gl_Position=O*vec4(BE,1);}",
	"wpsmain":"uniform sampler2D Q;uniform bvec3 S;uniform vec4 T;varying vec3 BS;varying vec2 BQ;void main(){vec4 a=texture2D(Q,BQ);if(S[0]&&a.a<.7){discard;}if(S[1]&&a.r<.2&&a.g<.2&&a.b<.2){discard;}if(S[2]&&a.r>.9&&a.g>.9&&a.b>.9){discard;}gl_FragColor=a*T;}",
	"wpsparticles":"uniform sampler2D Q;varying vec2 BQ;varying vec4 BR;void main(){gl_FragColor=texture2D(Q,BQ)*BR;}",
	"svscommon":"vec3 B(vec3 d,vec3 c,vec3 a,vec3 b){vec3 e;e.x=dot(d,c);e.y=dot(d,a);e.z=dot(d,b);return e;}",
	"svsstandard":"\n#define BW attribute\n#define EM vec3\n#define EN vec4\n#define OF normalize\nuniform mat4 O,U;uniform EM V,W;BW EM BE;BW EN BJ,BO,BG,BP;BW vec2 BK;varying EM BS,BT,BU,BV;varying vec2 BQ[4];\n#ifdef EXPLICITUV1\nBW vec2 BL;\n#endif\n#ifdef EXPLICITUV2\nBW vec2 BL,BM;\n#endif\n#ifdef EXPLICITUV3\nBW vec2 BL,BM,BN;\n#endif\nvoid C(EM c,EM b,EM d,EN a,EN h,out EM f,out EM e,out EM g){EN j=EN(c,1);EN i=EN(b,0);EN k=EN(d,0);EN l;mat4 m=A(a[0])*h[0];mat4 n=A(a[1])*h[1];mat4 o=A(a[2])*h[2];mat4 p=A(a[3])*h[3];l=EN(0);l+=m*j;l+=n*j;l+=o*j;l+=p*j;f=EM(l);l=EN(0);l+=m*i;l+=n*i;l+=o*i;l+=p*i;e=OF(EM(l));l=EN(0);l+=m*k;l+=n*k;l+=o*k;l+=p*k;g=OF(EM(l));}void main(){EM h,g,k;C(BE,EM(BJ),EM(BO),BG,BP,h,g,k);mat3 e=mat3(U);EM i=(U*EN(h,1)).xyz;EM f=OF(e*g);EM j=OF(e*k);EM a=OF(cross(f,j)*BJ.w);EM d=OF(W-i);BT=OF(B(d,j,a,f));EM b=OF(V-i);EM c=OF(b-W);BU=B(b,j,a,f);BV=B(c,j,a,f);BS=f;BQ[0]=BK;\n#ifdef EXPLICITUV1\nBQ[1]=BL;\n#endif\n#ifdef EXPLICITUV2\nBQ[1]=BL;BQ[2]=BM;\n#endif\n#ifdef EXPLICITUV3\nBQ[1]=BL;BQ[2]=BM;BQ[3]=BN;\n#endif\ngl_Position=O*EN(h*1.,1);}",
	"spscommon":"\n#define CY else\n#define DM return\n#define EN vec4\n#define FG sampler2D\nuniform vec3 X;varying vec3 BS,BT,BU,BV;varying vec2 BQ[4];struct K{bool a,e,f;float b,c,d,g;};vec3 D(EN a,vec3 c,K b){if(b.b==.0){c*=a.rgb;}CY if(b.b==1.){c*=a.rgb*2.;}CY if(b.b==2.){c+=a.rgb*a.a;}CY if(b.b==6.){c+=a.rgb;}CY if(b.b==3.){c=mix(c,a.rgb,a.a);}CY if(b.b==4.){c+=a.a*X;}CY if(b.b==5.){c+=a.a*X;}DM c;}EN E(float a,EN b){if(a==3.){b=b.rrrr;}CY if(a==4.){b=b.gggg;}CY if(a==5.){b=b.bbbb;}CY if(a==2.){b=b.aaaa;}CY if(a==.0){b.a=1.;}DM b;}vec2 F(K a){if(a.g==1.){DM BQ[1];}CY if(a.g==2.){DM BQ[2];}CY if(a.g==3.){DM BQ[3];}DM BQ[0];}EN G(FG a,K b){DM texture2D(a,F(b));}EN H(FG a,K b){EN d=G(a,b);EN c=E(b.c,d);if(b.d==1.){c=EN(mix(X,c.rgb,d.a),1);}CY if(b.d==2.){c=EN(mix(X,c.rgb,d.a),1);}if(b.e){c=EN(1)-c;}if(b.f){c=clamp(c,.0,1.);}DM c;}vec3 I(FG a){EN c=texture2D(a,BQ[0]);vec3 b;b.xy=2.*c.wy-1.;b.z=sqrt(max(.0,1.-dot(b.xy,b.xy)));DM b;}EN J(FG d,K a,float e,float c,vec3 b){EN f;if(a.a){f=H(d,a);}CY{f=EN(0);}float g=pow(max(-dot(BV,b),.0),e)*c;DM f*g;}",
	"spsstandard":"\n#define BY uniform\nBY float Y,Z,AA;BY vec4 AB;BY K AC,AE,AG,AI,AK,AM,AO,AQ,AS,AU,AW,AY,BA,BC;BY sampler2D AD,AF,AH,AJ,AL,AN,AP,AR,AT,AV,AX,AZ,BB,BD;void main(){vec3 b;vec4 f=AB;vec3 j;vec3 i;if(AW.a){j=I(AX);}else{j=BS;}float g=max(dot(j,BT),.0);if(g>.0){if(AC.a){vec4 d=H(AD,AC);b=D(d,b,AC);}if(AE.a){vec4 c=H(AF,AE);b=D(c,b,AE);}vec4 k=J(AH,AG,Y,Z,j);if(BA.a){vec4 h=H(BB,BA)*2.;i=h.rgb;}f.rgb=(b+k.rgb)*g;bool a=false;vec3 e;vec4 l;if(AK.a){l=H(AL,AK);if(AK.b==.0||AK.b==1.||AK.b==3.){f.rgb=D(l,f.rgb,AK);}else{e=D(l,e,AK);a=true;}}if(AM.a){l=H(AN,AM);if(!a&&(AM.b==.0||AM.b==1.||AM.b==3.)){f.rgb=D(l,f.rgb,AM);}else{e=D(l,e,AM);a=true;}}if(a){f.rgb+=e*AA;}}gl_FragColor=f;}",
	"spsspecialized":"\n#define BY uniform\n#define FG sampler2D\n#ifdef DIFFUSE_PASS\nBY K AC;BY FG AD;\n#endif\n#ifdef SPECULAR_PASS\nBY K AG;BY FG AH;BY float Y,Z;\n#endif\n#ifdef HIGHRES_NORMALS\nBY K AW;BY FG AX;\n#endif\n#ifdef EMISSIVE_PASS\nBY K AK,AM;BY FG AL,AN;BY float AA;\n#endif\n#ifdef DECAL_PASS\nBY K AE;BY FG AF;\n#endif\nvoid main(){vec4 b=vec4(0);vec3 f;\n#ifdef HIGHRES_NORMALS\nf=I(AX);\n#else\nf=BS;\n#endif\n#ifdef DIFFUSE_PASS\nb=H(AD,AC);\n#endif\n#ifdef NORMALS_PASS\nb=vec4(f,1);\n#endif\n#ifdef SPECULAR_PASS\nb=J(AH,AG,Y,Z,f);\n#endif\n#ifdef EMISSIVE_PASS\nbool a=false;vec3 d=vec3(0);vec4 g;if(AK.a){g=H(AL,AK);if(AK.b==.0||AK.b==1.||AK.b==3.){b.rgb=D(g,b.rgb,AK);}else{d=D(g,d,AK);a=true;}}if(AM.a){g=H(AN,AM);if(!a&&(AM.b==.0||AM.b==1.||AM.b==3.)){b.rgb=D(g,b.rgb,AM);}else{d=D(g,d,AM);a=true;}}if(a){b.rgb+=d.rgb*AA;}\n#endif\n#ifdef UNSHADED_PASS\nfloat e=max(dot(f,BT),.0);b=vec4(e,e,e,1);\n#endif\n#ifdef DECAL_PASS\nif(AE.a){vec4 c=H(AF,AE);b.rgb=D(c,b.rgb,AE);b.a=1.;}\n#endif\ngl_FragColor=b;}",
	"svsparticles":"uniform mat4 O;attribute vec3 BE;void main(){gl_Position=O*vec4(BE,1);}",
	"spsparticles":"void main(){gl_FragColor=vec4(1);}"
};