  return {
    setPerspective: setPerspective,
    setOrtho: setOrtho,
    loadIdentity: loadIdentity,
    translate: translate,
    rotate: rotate,
    scale: scale,
    lookAt: lookAt,
    multMat: multMat,
    pushMatrix: pushMatrix,
    popMatrix: popMatrix,
    createShader: createShader,
    shaderReady: shaderReady,
    bindShader: bindShader,
    getViewProjectionMatrix: getViewProjectionMatrix,
    getProjectionMatrix: getProjectionMatrix,
    getViewMatrix: getViewMatrix,
    loadTexture: loadTexture,
    textureOptions: textureOptions,
    bindTexture: bindTexture,
    createRect: createRect,
    createSphere: createSphere,
    createCube: createCube,
    createCylinder: createCylinder,
    ctx: ctx
  };
}