var Mdx = {};

var WORKER_NEW_MODEL = 1;
var WORKER_NEW_INSTANCE = 2;
var WORKER_NEW_GEOSET = 3;
var WORKER_NEW_SKELETON = 4;
var WORKER_NEW_LAYER = 5;
var WORKER_NEW_BATCHES = 6;
var WORKER_NEW_TEXTURES = 7;
var WORKER_UPDATE_INSTANCE = 8;
var WORKER_UPDATE_SKELETON = 9;
var WORKER_UPDATE_BATCH_VISIBILITIES = 10;
var WORKER_SET_SEQUENCE = 11;
var WORKER_UPDATE_INSTANCE_ROOT = 12;
var WORKER_NEW_SEQUENCES = 13;