export const TEAM_COLORS = [
  { name: 'Red', color: '#ff0402' },
  { name: 'Blue', color: '#0042ff' },
  { name: 'Teal', color: '#1be6ba' },
  { name: 'Purple', color: '#540081' },
  { name: 'Yellow', color: '#fffc00' },
  { name: 'Orange', color: '#ff8a0d' },
  { name: 'Green', color: '#20c000' },
  { name: 'Pink', color: '#e45bb0' },
  { name: 'Gray', color: '#949697' },
  { name: 'Light Blue', color: '#7ebff1' },
  { name: 'Dark Green', color: '#106247' },
  { name: 'Brown', color: '#4f2a05' },
  { name: 'Maroon', color: '#9c0000' },
  { name: 'Navy', color: '#0000c3' },
  { name: 'Turquoise', color: '#00ebff' },
  { name: 'Violet', color: '#bd00ff' },
  { name: 'Wheat', color: '#eccd86' },
  { name: 'Peach', color: '#f7a48b' },
  { name: 'Mint', color: '#c0ff80' },
  { name: 'Lavender', color: '#dcb9ec' },
  { name: 'Coal', color: '#4f4f55' },
  { name: 'Snow', color: '#ecf0ff' },
  { name: 'Emerald', color: '#00781e' },
  { name: 'Peanut', color: '#a46f33' },
  { name: 'Neutral', color: '#2e2d2e' },
];
